### ISSUE TITLE
Mac - Beim Start Fehler: java[11378] <Error>: The function ‘CGContextErase’ is obsolete

### ISSUE THREAD

**Issue by splattne** [xaverW/MediathekView#23]
Ich erhalte beim Starten von MediathekView__Mac_Start.command folgenden Fehler:

>java[11378] <Error>: The function ‘CGContextErase’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.
>Exception in thread "main" java.lang.UnsupportedClassVersionError: mediathek/Main : Unsupported major.minor version 51.0
>	at java.lang.ClassLoader.defineClass1(Native Method)
>	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
>	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
>	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
>	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
>	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
>	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
>	at java.security.AccessController.doPrivileged(Native Method)
>	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
>	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by splattne** [comment]
Die eigene Mac-Version funktioniert. Vielen Dank!
