### ISSUE TITLE
OpenJDK8: UnsatisfiedLinkError: no splashscreen in java.library.path

### ISSUE THREAD

**Issue by StarPicard** [xaverW/MediathekView#70]
MediathekView does not start with OpenJDK-V8
The following output is given:
`.  Proxy Authentication: not configured
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no splashscreen in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.SplashScreen$1.run(SplashScreen.java:124)
	at java.awt.SplashScreen$1.run(SplashScreen.java:122)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:121)
	at mediathek.MediathekGui.initializeSplashScreen(MediathekGui.java:214)
	at mediathek.MediathekGui.<init>(MediathekGui.java:225)
	at mediathek.Main$2.run(Main.java:175)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by xaverW** [comment]
MV starts with openJDK:
openjdk version "1.8.0_77" ist my Version

**Comment by derreisende77** [comment]
Maybe only headless installed??

**Comment by StarPicard** [comment]
Yes... sorry for extra work!
