### ISSUE TITLE
Nach Update auf Version 11 Exception beim Starten/Speichern der DB

### ISSUE THREAD

**Issue by daphee** [xaverW/MediathekView#73]
Habe gerade geupdatet. Heißt die Datei in dem Ordner, in den ich die vorige Version entzippt hatte, überschrieben.

Jetzt bleibt das Programm beim Starten hängen und ich bekomme folgende Exception:

``Exception in thread "AWT-EventQueue-0" java.lang.NoSuchFieldError: datumFilm
	at mediathek.daten.ListeBlacklist.checkDate(ListeBlacklist.java:221)
	at mediathek.daten.ListeBlacklist.checkFilm(ListeBlacklist.java:180)
	at mediathek.daten.ListeBlacklist.filterListe(ListeBlacklist.java:125)
	at mediathek.tool.MVListeFilme.checkBlacklist(MVListeFilme.java:29)
	at mediathek.gui.GuiFilme.init(GuiFilme.java:349)
	at mediathek.MediathekGui.initTabs(MediathekGui.java:728)
	at mediathek.MediathekGui.init(MediathekGui.java:582)
	at mediathek.MediathekGui.<init>(MediathekGui.java:289)
	at mediathek.Main$2.run(Main.java:175)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
``

Wenn ich dann meine (alte) .mediathek3/mediathek.xml Datei lösche, klappt der Start aber ich bekomme dann später diese Exception:

``Exception in thread "Thread-5" java.lang.NoSuchFieldError: datumFilm
	at mediathek.daten.ListeBlacklist.checkDate(ListeBlacklist.java:221)
	at mediathek.daten.ListeBlacklist.checkFilm(ListeBlacklist.java:180)
	at mediathek.daten.ListeBlacklist.filterListe(ListeBlacklist.java:125)
	at mediathek.tool.MVListeFilme.checkBlacklist(MVListeFilme.java:29)
	at mediathek.controller.FilmeLaden.undEnde(FilmeLaden.java:237)
	at mediathek.controller.FilmeLaden.access$300(FilmeLaden.java:48)
	at mediathek.controller.FilmeLaden$1.fertig(FilmeLaden.java:80)
	at msearch.filmlisten.MSImportFilmliste.fertigMelden(MSImportFilmliste.java:227)
	at msearch.filmlisten.MSImportFilmliste.access$100(MSImportFilmliste.java:30)
	at msearch.filmlisten.MSImportFilmliste$FilmeImportierenAutoThread.run(MSImportFilmliste.java:108)
	at java.lang.Thread.run(Thread.java:745)
``

Filme werden zwar geladen (Gesamtzahl steht unten links) aber es werden keine angezeigt.

Das Programm dann schließen und wieder öffnen zeigt jedes Mal das "Erster Start" Fenster, da ja die Datenbank nicht geschrieben werden konnte.

**Comment by xaverW** [comment]
lösche mal den ganzen Ordner:
.mediathek3

welches BS/Java-version??
