### ISSUE TITLE
Debian 8 (Jessie): Exception in thread "main" java.lang.UnsupportedClassVersionError: mediathek/Main : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Wikinaut** [xaverW/MediathekView#82]
On my fresh debian 8, the current git version throws

```
/dist/MediathekView__Linux.sh

"Exception in thread "main" java.lang.UnsupportedClassVersionError: mediathek/Main :
Unsupported major.minor version 52.0"
```

Any idea ?

Remark: ```apt-get install mediathekview``` pulled an outdated version 8, which appeared to work, but after seeing the version  info I decided to install from github.

**Comment by Wikinaut** [comment]
```
./MediathekView__Linux.sh 
Exception in thread "main" java.lang.UnsupportedClassVersionError: mediathek/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by criztovyl** [comment]
What does `java -version` say?

**Comment by xaverW** [comment]
tha actual version of the program, needs java 8

**Comment by Wikinaut** [comment]
@xaverW ok, thanks. Wasn't clear. Perhaps this can be added as check ? I don't know. (closing now).

**Comment by HJarausch** [comment]
I have the same problem on my Gentoo machine.
java -version    gives
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

that is the latest version of Oracle's Java SE Development Kit

**Comment by xaverW** [comment]
did you read the "Hilfe__bitte_lesen.txt"?

* Java ist nicht oder nicht in der richtigen Version installiert (Java8). Zum 
  Java-Download: http://java.com/de/
  Unter Linux müssen dazu 2 Pakete installiert werden!

  bei arch: java-openjfx und jre8-openjdk,
  bei Ubuntu 16.04: default-jre (entspricht openjdk-8-jre) und openjfx

Oracle has all in, openJdk nedds two

**Comment by xaverW** [comment]
and in the wiki is this (READ)
https://sourceforge.net/p/zdfmediathk/wiki/Linux/#debian-8-gnome
